name: Scrape Tables with Playwright

on:
  push:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies (24f1000666@ds.study.iitm.ac.in)
      run: |
        pip install -r requirements.txt
        python -m playwright install chromium

    - name: Run Scraper
      run: python scrape_sum.py
